### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by vilmer22** [Emberium/SimpleQIWI#1]
i install all , and when i am trying write print(api.balance) 

>>> print(api.balance)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\SimpleQIWI\Session.py", line 80, in balanc
e
    balances = self.full_balance
  File "C:\Python27\lib\site-packages\SimpleQIWI\Session.py", line 70, in full_b
alance
    return self._get_balance()
  File "C:\Python27\lib\site-packages\SimpleQIWI\Session.py", line 131, in _get_
balance
    raise QIWIAPIError(json)
SimpleQIWI.Errors.QIWIAPIError: {u'errorCode': u'auth.forbidden', u'serviceName'
: u'funding-sources', u'userMessage': u'Access denied'}

please help , what does it mean?
(i did it with cmd and run as administrator)

**Comment by ghost** [comment]
maybe broken api key (auth failed)

**Comment by softskate** [comment]
If shows balance but can't show payment history or something like, then you entered your number wrong. If even balance doesn't show, so you entered api code wrong
